run:
  timeout: 5m
  tests: false
  go: "1.23"

linters:
  disable-all: true
  enable:
    - bodyclose
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - asciicheck
    - cyclop
    - dupl
    - dupword
    - errorlint
    - copyloopvar
    - forcetypeassert
    - funlen
    - gocritic
    - gofmt
    - goimports
    - gosec
    - gosmopolitan
    - loggercheck
    - makezero
    - mirror
    - noctx
    - prealloc
    - predeclared
    - stylecheck
    - thelper
    - wastedassign
    - wsl
    - wrapcheck

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

linters-settings:
  govet:
    enable-all: true
  wrapcheck:
    ignoreSigRegexps:
      - \(github\.com\/labstack\/echo\/v4\.Context\).*