pre-push:
  parallel: true
  commands:
    generate:
      tags: generate code
      run: task generate
    lint:
      tags: run linter
      run: task lint
      glob: "*.go"
    test:
      tags: run tests
      run: task test
      glob: "*.go"