apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: post-forwarder
build:
  artifacts:
    - image: post-forwarder
      ko:
        main: ./internal/post-forwarder
manifests:
  rawYaml:
    - docker/deployment.yaml
