apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: post-forwarder
build:
  artifacts:
    - image: post-forwarder
      ko:
        main: ./internal/post-forwarder
    - image: chat-id-checker
      ko:
        main: ./internal/chat-id-checker
deploy:
  statusCheckDeadlineSeconds: 300
  tolerateFailuresUntilDeadline: true
manifests:
  rawYaml:
    - k8s/redis.yaml
    - k8s/post-forwarder.yaml
    - k8s/chat-id-checker.yaml
