apiVersion: v1
kind: Service
metadata:
  name: post-forwarder
  namespace: post-forwarder
spec:
  selector:
    app: post-forwarder
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-forwarder
  namespace: post-forwarder
  labels:
    app: post-forwarder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-forwarder
  template:
    metadata:
      labels:
        app: post-forwarder
    spec:
      containers:
      - name: post-forwarder
        image: post-forwarder
        envFrom:
          - secretRef:
              name: post-forwarder
        ports:
          - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-id-checker
  namespace: post-forwarder
  labels:
    app: chat-id-checker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-id-checker
  template:
    metadata:
      labels:
        app: chat-id-checker
    spec:
      containers:
        - name: chat-id-checker
          image: chat-id-checker
          envFrom:
            - secretRef:
                name: post-forwarder
