// Code generated by mockery v2.33.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MessageDestination is an autogenerated mock type for the MessageDestination type
type MessageDestination struct {
	mock.Mock
}

// Send provides a mock function with given fields: ctx, service, msg
func (_m *MessageDestination) Send(ctx context.Context, service string, msg string) error {
	ret := _m.Called(ctx, service, msg)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, service, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMessageDestination creates a new instance of MessageDestination. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageDestination(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageDestination {
	mock := &MessageDestination{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
