// Code generated by gowrap. DO NOT EDIT.
// template: https://raw.githubusercontent.com/adlandh/gowrap-templates/main/sentry.gotmpl
// gowrap: http://github.com/hexdigest/gowrap

package wrappers

//go:generate gowrap gen -p github.com/adlandh/post-forwarder/internal/post-forwarder/domain -i MessageDestination -t https://raw.githubusercontent.com/adlandh/gowrap-templates/main/sentry.gotmpl -o MessageDestinationWithSentry.go -l ""

import (
	"context"

	helpers "github.com/adlandh/gowrap-templates/helpers/sentry"
	"github.com/adlandh/post-forwarder/internal/post-forwarder/domain"
	"github.com/getsentry/sentry-go"
)

// MessageDestinationWithSentry implements domain.MessageDestination interface instrumented with opentracing spans
type MessageDestinationWithSentry struct {
	domain.MessageDestination
	_instance      string
	_spanDecorator func(span *sentry.Span, params, results map[string]interface{})
}

// NewMessageDestinationWithSentry returns MessageDestinationWithSentry
func NewMessageDestinationWithSentry(base domain.MessageDestination, instance string, spanDecorator ...func(span *sentry.Span, params, results map[string]interface{})) MessageDestinationWithSentry {
	d := MessageDestinationWithSentry{
		MessageDestination: base,
		_instance:          instance,
	}

	if len(spanDecorator) > 0 && spanDecorator[0] != nil {
		d._spanDecorator = spanDecorator[0]
	} else {
		d._spanDecorator = helpers.SpanDecorator
	}

	return d
}

// Send implements domain.MessageDestination
func (_d MessageDestinationWithSentry) Send(ctx context.Context, service string, msg string) (err error) {
	span := sentry.StartSpan(ctx, _d._instance+".domain.MessageDestination.Send", sentry.TransactionName("domain.MessageDestination.Send"))
	ctx = span.Context()

	defer func() {
		_d._spanDecorator(span, map[string]interface{}{
			"ctx":     ctx,
			"service": service,
			"msg":     msg}, map[string]interface{}{
			"err": err})
		span.Finish()
	}()
	return _d.MessageDestination.Send(ctx, service, msg)
}
