// Code generated by gowrap. DO NOT EDIT.
// template: https://raw.githubusercontent.com/adlandh/gowrap-templates/main/sentry.gotmpl
// gowrap: http://github.com/hexdigest/gowrap

package wrappers

//go:generate gowrap gen -p github.com/adlandh/post-forwarder/internal/post-forwarder/domain -i MessageDestination -t https://raw.githubusercontent.com/adlandh/gowrap-templates/main/sentry.gotmpl -o MessageDestinationWithSentry.go -l ""

import (
	"context"
	"encoding/json"
	"net/http"

	"github.com/adlandh/post-forwarder/internal/post-forwarder/domain"
	"github.com/getsentry/sentry-go"
)

// MessageDestinationWithSentry implements domain.MessageDestination interface instrumented with opentracing spans
type MessageDestinationWithSentry struct {
	domain.MessageDestination
	_instance      string
	_spanDecorator func(span *sentry.Span, params, results map[string]interface{})
}

// NewMessageDestinationWithSentry returns MessageDestinationWithSentry
func NewMessageDestinationWithSentry(base domain.MessageDestination, instance string, spanDecorator ...func(span *sentry.Span, params, results map[string]interface{})) MessageDestinationWithSentry {
	d := MessageDestinationWithSentry{
		MessageDestination: base,
		_instance:          instance,
	}

	if len(spanDecorator) > 0 && spanDecorator[0] != nil {
		d._spanDecorator = spanDecorator[0]
	} else {
		d._spanDecorator = d._defaultSpanDecorator
	}

	return d
}

func (_d MessageDestinationWithSentry) _defaultSpanDecorator(span *sentry.Span, params, results map[string]interface{}) {
	for p := range params {
		switch params[p].(type) {
		case context.Context:
		default:
			val, _ := json.Marshal(params[p])
			span.SetTag("param."+p, string(val))
		}
	}

	for p := range results {
		switch results[p].(type) {
		case context.Context:
		case *http.Response:
			val, _ := json.Marshal(results[p].(*http.Response).Header)
			span.SetTag("result."+p+".headers", string(val))
		default:
			val, _ := json.Marshal(results[p])
			span.SetTag("result."+p, string(val))
		}
	}
}

// Send implements domain.MessageDestination
func (_d MessageDestinationWithSentry) Send(ctx context.Context, service string, msg string) (err error) {
	span := sentry.StartSpan(ctx, _d._instance+".domain.MessageDestination.Send", sentry.TransactionName("domain.MessageDestination.Send"))
	ctx = span.Context()

	defer func() {
		_d._spanDecorator(span, map[string]interface{}{
			"ctx":     ctx,
			"service": service,
			"msg":     msg}, map[string]interface{}{
			"err": err})
		if err != nil {
			span.SetTag("event", "error")
			span.SetTag("message", err.Error())
		}

		span.Finish()
	}()
	return _d.MessageDestination.Send(ctx, service, msg)
}
