// Code generated by gowrap. DO NOT EDIT.
// template: https://raw.githubusercontent.com/adlandh/gowrap-templates/main/zap.gotmpl
// gowrap: http://github.com/hexdigest/gowrap

package wrappers

//go:generate gowrap gen -p github.com/adlandh/post-forwarder/internal/post-forwarder/domain -i MessageDestination -t https://raw.githubusercontent.com/adlandh/gowrap-templates/main/zap.gotmpl -o MessageDestinationWithZap.go -l ""

import (
	"context"

	"github.com/adlandh/post-forwarder/internal/post-forwarder/domain"
	"go.uber.org/zap"
)

// MessageDestinationWithZap implements domain.MessageDestination that is instrumented with zap logger
type MessageDestinationWithZap struct {
	_base domain.MessageDestination
	_log  *zap.Logger
}

// NewMessageDestinationWithZap instruments an implementation of the domain.MessageDestination with simple logging
func NewMessageDestinationWithZap(base domain.MessageDestination, log *zap.Logger) MessageDestinationWithZap {
	return MessageDestinationWithZap{
		_base: base,
		_log:  log,
	}
}

// Send implements domain.MessageDestination
func (_d MessageDestinationWithZap) Send(ctx context.Context, service string, msg string) (err error) {
	_d._log.Debug("MessageDestinationWithZap: calling Send", zap.Any("params", map[string]interface{}{
		"ctx":     ctx,
		"service": service,
		"msg":     msg}))
	defer func() {
		if err != nil {
			_d._log.Warn("MessageDestinationWithZap: method Send returned an error", zap.Error(err), zap.Any("result", map[string]interface{}{
				"err": err}))
		} else {
			_d._log.Debug("MessageDestinationWithZap: method Send finished", zap.Any("result", map[string]interface{}{
				"err": err}))
		}
	}()
	return _d._base.Send(ctx, service, msg)
}
