openapi: 3.0.3
info:
  title: Port Forwarder webhook
  description: Port Forwarder webhook
  version: 1.1.0
servers:
  - url: 'http://localhost:8080'
components:
  schemas:
    Message:
      type: object
      required: [id,created_at,message]
      properties:
        id:
          type: string
        created_at:
          type: string
          format: date-time
        message:
          type: string
paths:
  /:
    get:
      operationId: healthCheck
      description: health check endpoint
      responses:
        '200':
          description: ok
          content:
            text/plain:
              schema:
                type: string
                default: Ok
  /api/{token}/{service}:
    post:
      operationId: postWebhook
      description: POST webhook endpoint
      parameters:
        - in: path
          name: token
          required: true
          schema:
            type: string
          description: api token
        - in: path
          name: service
          required: true
          schema:
            type: string
          description: name of service
      responses:
        '200':
          description: ok
    get:
      operationId: getWebhook
      description: GET webhook endpoint
      parameters:
        - in: path
          name: token
          required: true
          schema:
            type: string
          description: api token
        - in: path
          name: service
          required: true
          schema:
            type: string
          description: name of service
      responses:
        '200':
          description: ok
  /api/message/{id}:
    get:
      operationId: showMessage
      description: show long message
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: message id
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '404':
          description: not found